**Q1.]**

In [1]:

# 🔹 Tasks:
# Display first 3 rows
# Find average marks
# Filter students who scored more than 85
# Count how many students are in each subject
# Add a new column "Result" → "Pass" if marks ≥ 80 else "Fail"
# Sort dataframe by Marks in descending order

In [2]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Karan", "Neha", "Rahul"],
    "Marks": [85, 90, 78, 92, 88],
    "Subject": ["Math", "Science", "Math", "Science", "Math"]
}

df = pd.DataFrame(data)

In [3]:
data

{'Name': ['Aman', 'Riya', 'Karan', 'Neha', 'Rahul'],
 'Marks': [85, 90, 78, 92, 88],
 'Subject': ['Math', 'Science', 'Math', 'Science', 'Math']}

In [4]:
df.head(3)

    Name  Marks  Subject
0   Aman     85     Math
1   Riya     90  Science
2  Karan     78     Math

In [5]:
df.describe()

           Marks
count   5.000000
mean   86.600000
std     5.458938
min    78.000000
25%    85.000000
50%    88.000000
75%    90.000000
max    92.000000

In [6]:
avg=df["Marks"].mean()
print(avg)

86.6

In [7]:
# Score greater than 85
great=df[df["Marks"]>85]
print(great)

    Name  Marks  Subject
1   Riya     90  Science
3   Neha     92  Science
4  Rahul     88     Math

In [8]:
print(df["Subject"].value_counts())

Subject
Math       3
Science    2
Name: count, dtype: int64

In [9]:
df["Result"] = ["Pass" if x >= 80 else "Fail" for x in df["Marks"]]

In [10]:
df

    Name  Marks  Subject Result
0   Aman     85     Math   Pass
1   Riya     90  Science   Pass
2  Karan     78     Math   Fail
3   Neha     92  Science   Pass
4  Rahul     88     Math   Pass

In [11]:
df_sorted = df.sort_values(by="Marks", ascending=False)
print(df_sorted)

    Name  Marks  Subject Result
3   Neha     92  Science   Pass
1   Riya     90  Science   Pass
4  Rahul     88     Math   Pass
0   Aman     85     Math   Pass
2  Karan     78     Math   Fail

Q2.]

In [12]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Karan", "Riya", "Aman", "Neha"],
    "Marks": [85, 90, 78, 90, 85, 92],
    "Subject": ["Math", "Science", "Math", "Science", "Math", "Science"]
}

df = pd.DataFrame(data)

In [13]:
# Tasks:
# Find duplicate rows
# Remove duplicates based on Name and Marks
# Find average marks of each subject
# Filter students who scored ≥ 85
# Sort data by Marks (descending)
# Find highest marks in each subject

In [35]:
df[df.duplicated()]

   Name  Marks  Subject
3  Riya     90  Science
4  Aman     85     Math

In [17]:
df.drop_duplicates(subset=["Name","Marks","Subject"])

    Name  Marks  Subject
0   Aman     85     Math
1   Riya     90  Science
2  Karan     78     Math
5   Neha     92  Science

In [18]:
df.drop_duplicates(subset=["Name","Marks"])

    Name  Marks  Subject
0   Aman     85     Math
1   Riya     90  Science
2  Karan     78     Math
5   Neha     92  Science

In [20]:
df.drop_duplicates(subset=["Subject"])
avg=df["Marks"].mean

In [21]:
avg

<bound method Series.mean of 0    85
1    90
2    78
3    90
4    85
5    92
Name: Marks, dtype: int64>

In [31]:
df[df["Marks"]>=85].drop_duplicates(subset="Name")

   Name  Marks  Subject
0  Aman     85     Math
1  Riya     90  Science
5  Neha     92  Science

In [33]:
sort=df.sort_values(by="Marks",ascending=False)

In [34]:
sort

    Name  Marks  Subject
5   Neha     92  Science
1   Riya     90  Science
3   Riya     90  Science
0   Aman     85     Math
4   Aman     85     Math
2  Karan     78     Math